version: '3.9'

services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - FLASK_ENV=production
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: gunicorn -b 0.0.0.0:8000 run:create_app()

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis:6379/0
    command: celery -A tasks.celery worker --loglevel=info

  redis:
    image: redis:alpine
    command: ["redis-server", "--requirepass", ""]
